language: python
sudo: false
python:
    - 'nightly'
    - '3.6'
    - '3.5'
    - '3.4'
    - '3.3'
    - '3.2'
    - '2.7'
    - '2.6'
    - 'pypy'
    - 'pypy3'
install:
    - python setup.py install
script: nosetests
matrix:
  allow_failures:
    - python: 'nightly'
    - python: 'pypy3'
    - python: 'pypy'
    - python: '2.6
  fast_finish: true
